version: "3"
services:
    node:
        build: .
        ports:
            - "3000"
        volumes:
            - "./src:/app/src"
            - "./public:/app/public"
    nginx:
        build: "./nginx"
        ports:
            - "80:80"
        depends_on:
            - "node"